name: CI and Release Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*'  # Trigger on version tags for releases

jobs:
  build-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          # Linux Builds
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            arch: x86_64
            features: ""
            label: "standard"

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            arch: x86_64
            features: "zip"
            label: "full"

          # macOS Builds
          - os: macos-latest
            target: x86_64-apple-darwin
            arch: x86_64
            features: ""
            label: "standard"

          - os: macos-latest
            target: x86_64-apple-darwin
            arch: x86_64
            features: "zip"
            label: "full"

          # Windows Builds
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            arch: x86_64
            features: ""
            label: "standard"

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            arch: x86_64
            features: "zip"
            label: "full"

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check
        run: |
          if [ "${{ matrix.features }}" == "zip" ]; then
            cargo check --features "zip"
          else
            cargo check
          fi

      - name: Build
        run: |
          if [ "${{ matrix.features }}" == "zip" ]; then
            cargo build --release --features "zip"
          else
            cargo build --release
          fi

      # Zipping for Linux and macOS
      - name: Zip the build on Linux and macOS
        if: runner.os != 'Windows'
        run: |
          mkdir -p artifacts
          zip -j artifacts/${{ github.repository }}-${{ matrix.target }}-${{ matrix.label }}-${{ matrix.os }}.zip target/release/my_executable_name

      # Zipping for Windows
      - name: Zip the build on Windows
        if: runner.os == 'Windows'
        run: |
          mkdir -p artifacts
          powershell Compress-Archive -Path target/release/my_executable_name.exe -DestinationPath artifacts/${{ github.repository }}-${{ matrix.target }}-${{ matrix.label }}-${{ matrix.os }}.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ github.repository }}-${{ matrix.target }}-${{ matrix.label }}-${{ matrix.os }}"
          path: "artifacts/${{ github.repository }}-${{ matrix.target }}-${{ matrix.label }}-${{ matrix.os }}.zip"
